# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DataFrameLoader": "00_DataFrameLoader.ipynb",
         "PreProcessor": "01_PreProcessor.ipynb",
         "MLPipeline": "02_MLPipeline.ipynb"}

modules = ["DataFrameLoader.py",
           "PreProcessor.py",
           "MLPipeline.py"]

doc_url = "https://psmathur.github.io/tabular_ml_toolkit/"

git_url = "https://github.com/psmathur/tabular_ml_toolkit/tree/master/"

def custom_doc_links(name): return None
